---
deployment:
  tasks:
    - export DEPLOYPATH=/home/atlasaiteam/public_html/
    - /bin/cp client/main.js $DEPLOYPATH
    - /bin/cp client/*.html $DEPLOYPATH
    - /bin/cp client/style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - export DEPLOYPATH=/home/atlasaiteam/openapi.atlasaiteam.web.illinois.edu/
    - /bin/cp server/server.js $DEPLOYPATH
    - /bin/touch $DEPLOYPATH/test.txt
    - /bin/echo "This is the new deploy path $(DEPLOYPATH)" >> $DEPLOYPATH/test.txt